import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers"; // ✅ Providersコンポーネントをインポート
import Link from "next/link";
import AppLayout from "@/components/AppLayout"; // AppLayoutはProvidersの内側に配置

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <header>
          <nav className="w-full mx-auto">
            <ul className="w-full mx-auto flex justify-center">
              <li className="m-4">
                <Link href="/mypage">マイページ</Link>
              </li>
              <li className="m-4">
                <Link href="/">トップページ</Link>
              </li>
              {/* <li className="m-4">
                <Link href="/login">ログアウト</Link>
              </li> */}
            </ul>
          </nav>
        </header>
        {/* ✅ ProvidersコンポーネントでAppLayoutをラップ */}
        <Providers>
          <AppLayout>{children}</AppLayout>
        </Providers>
      </body>
    </html>
  );
}